[package]
name = "quick-error-ice"
version = "0.1.0"
publish = false
authors = ["Milkey Mouse <milkeymouse@meme.institute>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quick-error = "1.2.3"
